name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          cd ..
          ls -la
          echo "Current working directory structure:"
          find . -type f -name "package.json"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.0'
          
      - name: Navigate to frontend
        run: |
          cd $GITHUB_WORKSPACE/frontend
          pwd
          ls -la
          
      - name: Install dependencies
        working-directory: $GITHUB_WORKSPACE/frontend
        run: npm install

      - name: Build
        working-directory: $GITHUB_WORKSPACE/frontend
        env:
          CI: false
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          entryPoint: './frontend'