name: Firebase CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Dependencies installed successfully"
      
    - name: Build React App
      run: |
        echo "Building React app..."
        npm run build
        echo "Build completed"
        
    - name: Install Firebase Tools
      run: |
        echo "Installing Firebase tools..."
        npm install -g firebase-tools
        echo "Firebase tools installed"
        
    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        echo "Starting Firebase deployment..."
        echo "Using project ID: $PROJECT_ID"
        firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project "$PROJECT_ID" --json
        echo "Firebase deployment completed"

    - name: Deployment Status
      if: always()
      run: |
        echo "Deployment job completed"
        echo "Check the Firebase Console for deployment status"